### ISSUE TITLE
Trailing Slash on the first page of pagination

### ISSUE THREAD

**Issue by tiwka19** [philnash/astro-components#4]
If you paste a slash in the url on the first page of pagination, the page will not give 404. So that /articles/ and /articles// will be indexed.

**Comment by philnash** [comment]
Thanks for the report, and sorry I only just saw this. I will take a look into this.

**Comment by tiwka19** [comment]
> Thanks for the report, and sorry I only just saw this. I will take a look into this.

I'm sorry, but when are you going to be able to fix this

**Comment by philnash** [comment]
Thanks for the reminder @tiwka19. I just took a look at this and I don't think it's an issue with this plugin. This plugin only generates pagination links, it doesn't handle responding to URLs. That is up to your web host/server and Astro itself.

I had a quick look around and [CloudFlare offers ways to normalize URLs](https://developers.cloudflare.com/rules/normalization/settings/), there are [long guides on this for Netlify](https://answers.netlify.com/t/support-guide-how-can-i-alter-trailing-slash-behaviour-in-my-urls-will-enabling-pretty-urls-help/31191) (and notably, [Astro's blog itself](https://astro.build/blog///) is hosted on Netlify and 301 redirects if you enter multiple trailing slashes) and I found a blog post on [how to handle this if hosting Astro sites on Vercel](https://noahflk.com/blog/trailing-slashes-astro#:~:text=Fixing%20the%20issue,file%20in%20the%20project%20root.&text=Now%20all%20URLs%20with%20trailing,same%20URL%20without%20trailing%20slashes.).

I am confident this is an issue between Astro and wherever you host your application, so I'm going to close this. If you have further thoughts or ideas on why this plugin might be responsible, please feel free to re-open. Thanks!
