### ISSUE TITLE
Astro 4

### ISSUE THREAD

**Issue by zgoda** [philnash/astro-components#5]
Astro 4 has been released and it seems to work fine with astro-pagination v0.3.0.

**Comment by tiwka19** [comment]
@philnash Please accept the PR

**Comment by philnash** [comment]
Oh hey, sorry. I didn't see this issue in my notifications. I will take a look at this today. Thanks for making the PR!

**Comment by tiwka19** [comment]
> Oh hey, sorry. I didn't see this issue in my notifications. I will take a look at this today. Thanks for making the PR!

Hi. You didn't forget?

**Comment by philnash** [comment]
This is now released as version 0.4.0.

Thanks for raising the issue, and bugging me about it! I didn't mean to overlook it. :)
